fix: Disable save previous URL
michalsn/codeigniter-htmx pull request #82
Opened 2024-11-05 14:01 UTC by neznaika0

Closes #81 
Copied `isWeb()` - it private method
The test may be inaccurate, correct it

2024-11-05 20:32 UTC, michalsn commented
I have second thoughts on this topic. When working with htmx, we may often want the page loaded by the htmx request to be stored as the previous URL.

My point is that in some cases this can be helpful, but for others, it will be a problem... so IMO we should make this option configurable.

Maybe `$storePreviousURL` option in the config file, with the default value set to `true` to preserve BC?

2024-11-05 20:44 UTC, neznaika0 commented
An example of specific cases? Yes, the setup is not a problem

2024-11-05 21:23 UTC, michalsn commented
> An example of specific cases?

An example would be using htmx in the navigation to simply navigate to another page. In that case, we won't be storing the previous URL in the session at all.

When AJAX headers are used, it is the user's choice. We will not override the default behavior of the framework.

2024-11-05 21:36 UTC, neznaika0 commented
No 😄 . An example where the previous URL is needed.
In the **userform > formhandler > userform** chain, sometimes the previous URL may be **formhandler**. 
I want to avoid this. 

Plus, there are questions about the framework when working with browser tabs... there, too, the URL is overwritten.

I'll update the PR tomorrow. I would be grateful if we discuss it in more detail.

2024-11-05 21:44 UTC, michalsn commented
It is not important where it will be used, only whether it will return correct data. If you disable updating the previous URL for htmx requests, then it may have an incorrect value.

> Plus, there are questions about the framework when working with browser tabs... there, too, the URL is overwritten.

Yes, the same way as for traditional requests - we won't change that.

2024-11-06 08:49 UTC, michalsn requested changes

2024-11-06 08:49 UTC, michalsn commented on docs/configuration.md
> +In the **/home > /htmx-request > /home** query chain, you can sometimes get an unexpected result if the previous URL is saved between requests. Instead of **/home**, you will get **/htmx-request**. T
```suggestion
Specifies whether the HTMX request URL should be stored in the session, for use with the `previous_url()` helper function.
For more information, see the [user guide](https://codeigniter.com/user_guide/helpers/url_helper.html#previous_url).

Basically, if you use HTMX extensively, including for navigating your site, you will probably want to leave it as `true`,
and in cases where storing the request is not desirable, even if it uses HTMX, you can use custom header, to indicate the
AJAX call or [ajax-header](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/ajax-header/README.md) extension,
which will add the necessary headers automatically. URLs from AJAX requests are always excluded from session storage.
```

2024-11-06 08:49 UTC, michalsn commented on src/CodeIgniter.php
> + */
```suggestion
use CodeIgniter\CodeIgniter as BaseCodeIgniter;
use CodeIgniter\HTTP\CLIRequest;
use CodeIgniter\HTTP\DownloadResponse;
use CodeIgniter\HTTP\RedirectResponse;
use CodeIgniter\HTTP\URI;
use Michalsn\CodeIgniterHtmx\HTTP\IncomingRequest;

/**
 * @property CLIRequest|IncomingRequest|null $request
 */
```

2024-11-06 08:49 UTC, michalsn commented on src/CodeIgniter.php
> +        }
```suggestion
        // Ignore AJAX requests
        if (method_exists($this->request, 'isAJAX') && $this->request->isAJAX()) {
            return;
        }

        // Ignore HTMX requests
        if (config('Htmx')->storePreviousURL === false
            && method_exists($this->request, 'isHTMX') && $this->request->isHTMX()) {
            return;
        }
```

2024-11-06 08:49 UTC, michalsn commented on src/Config/Htmx.php
> +     */
```suggestion
    /**
     * Enable / disable storing previous URLs for HTMX requests.
     */
```

2024-11-06 08:49 UTC, michalsn commented on tests/CodeIgniterTest.php
> +    public function testIsHTMXNotSavePreviousURL(): void
Please fix the test name and split it, so we test one scenario at a time.

2024-11-06 09:28 UTC, neznaika0 commented
You have almost completely corrected the PR. Fix it faster for you

2024-11-06 14:51 UTC, michalsn approved these changes
You did 90% of the work here. Thank you.

2024-11-06 14:51 UTC, merged

2024-12-06 07:48 UTC, neznaika0 commented
@michalsn I caught BC :smile: 
Let's say there is a "Show deleted" checkbox in the list of users. After clicking, HTMX changes the URI in the browser, but not in the history. If we click another button/link and try to return to the current URI (as `previous_url()`), it will turn out to be the old one (before clicking the "Show deleted" button)
Now I fully understand your pagination example.

So I haven't completely solved my problem.

2024-12-06 08:04 UTC, michalsn commented
What is your problem? Sometimes you want to store the `previousURL` even if it's disabled?
Or are you referring to the browser history?

2024-12-06 08:18 UTC, neznaika0 commented
The example with pagination is simpler: 
1. Go to **/users**
2. Click to pages Next/Back from HTMX and stop at **/users?page=10**
3. Click on the button with HTMX **/users/ban/33** and return to the same page (via `previous_url()`) Ops.. We should go back to **/users?page=10** but the story is disabled - we get to **/users**

Now I have forgotten the exact example of the initial problem. But apparently this is not how it was planned.

2024-12-06 08:27 UTC, michalsn commented
Why not use `ajax-header` extension for places where you want to store the URL?

2024-12-06 08:45 UTC, neznaika0 commented
Let's leave this question for now. When I find the exact example, I'll come back.